### Create a new blog with authentication
POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3MmMwZDdhMjM3MGQ2MzY0NTcxNDE3ZCIsImlhdCI6MTczMTE5MzkwOX0.x2hhdp2Dxq3AZF3-ZrpLUzun_gtibQzAmXsCYCgid14

{
  "title": "the new way 3.",
  "author": "ignacio",
  "url": "https://ignacio.net",
  "likes": 13
}

### Delete one blog
DELETE http://localhost:3003/api/blogs/672feb964809fab534d2ae91
Authorization: Bearer eyJdhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3MmMwZDdhMjM3MGQ2MzY0NTcxNDE3ZCIsImlhdCI6MTczMTE5MzkwOX0.x2hhdp2Dxq3AZF3-ZrpLUzun_gtibQzAmXsCYCgid14

### Update a blog by id
PUT http://localhost:3003/api/blogs/6727fde93c0b798af73a13d1
Content-Type: application/json

{
  "title": "UPdated title.",
  "likes": 27
}