### Create a new blog with authentication
POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3MmMwZDdhMjM3MGQ2MzY0NTcxNDE3ZCIsImlhdCI6MTczMTIwMDAyOH0.4EcMy8eCDFaLe34vfvIgtqm3QP_ZlynRln0-oxE8Y1U

{
  "title": "the new way 4.",
  "author": "ignacio",
  "url": "https://ignacio.net",
  "likes": 13
}

### Delete one blog
DELETE http://localhost:3003/api/blogs/67300449d52dda035b5bd1f4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3MmMwZDdhMjM3MGQ2MzY0NTcxNDE3ZCIsImlhdCI6MTczMTIwMDAyOH0.4EcMy8eCDFaLe34vfvIgtqm3QP_ZlynRln0-oxE8Y1U

### Update a blog by id
PUT http://localhost:3003/api/blogs/6727fde93c0b798af73a13d1
Content-Type: application/json

{
  "title": "UPdated title.",
  "likes": 27
}